spring:
  application:
    name: department-service

  datasource:
    url: jdbc:sqlserver://employee-microservice.database.windows.net:1433;databaseName=department_db;encrypt=true;trustServerCertificate=true
    username: sqladmin@employee-microservice
    password: Arpitha@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/